name: Sync Fork and Comment on PR

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  check-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          repository: ${{ github.repository }}

      - name: Check if PR branch is behind main
        id: check_behind
        run: |
          git fetch origin main
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "You are up to date with main."
          else
            echo "Your branch is behind main."  # Added message for clarity
            echo "Please sync your branch with main."  # Added message for user guidance
            exit 1
          fi
